name: test
on: workflow_dispatch
env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      # 下载LSPatch
      - name: Download LSPatch
        run: gh release download --repo LSPosed/LSPatch --pattern lspatch.jar

      # 下载待修补的应用
      - name: Download novelapp
        run: gh release download -O app.apk --repo cinit/QAuxiliary --pattern 'Fanqie-5.8.5.18.apk'

      # 使用GitHub CLI下载模块最新Release版本
      - name: 下载模块
        run: |
          gh release download -O hook.apk --repo cinit/QAuxiliary --pattern 'HookFanqie-5.8.5.18-hook.apk'

      # 修补
      - run: java -jar lspatch.jar app.apk -m hook.apk
